#!/bin/bash

if [[ $EUID > 0 ]]; then
    # Non-root run
    kate $@
else
    # Sudo or root run
    if SUDO_EDITOR=kate sudoedit $@ >/dev/null 2>&1; then
        # File must be edited with sudo
        SUDO_EDITOR=kate sudoedit $@
    else
        # File can be edited without sudo
        sudo -u $SUDO_USER /usr/bin/kate $@ >/dev/null 2>&1
    fi
fi
